/** PostHog product analytics event names — keep in sync with founder dashboard queries. */
export type AnalyticsEvent =
  // Landing & beta
  | "landing_page_viewed"
  | "beta_cta_clicked"
  | "language_selected"
  // Authentication
  | "signup_started"
  | "signup_completed"
  | "email_verified"
  | "verification_reminder_sent"
  | "login"
  | "login_completed"
  | "logout"
  | "account_deleted"
  // Onboarding
  | "onboarding_started"
  | "child_profile_created"
  | "child_profile_updated"
  | "parenting_goals_selected"
  | "current_challenges_selected"
  | "connect_area_selected"
  | "onboarding_completed"
  | "onboarding_skipped"
  | "first_plan_generated"
  | "first_session_dashboard_viewed"
  | "first_journey_started"
  | "wow_moment_viewed"
  | "hero_feature_recommended"
  | "returning_session_viewed"
  | "todays_journey_started"
  | "hero_feature_clicked"
  | "continue_journey"
  | "time_to_first_hero"
  | "learning_plan_generated"
  | "learning_plan_viewed"
  | "weekly_report_viewed"
  | "growth_journey_viewed"
  | "growth_mission_started"
  | "growth_mission_completed"
  | "growth_skill_viewed"
  | "growth_roadmap_opened"
  | "family_adventures_viewed"
  | "family_adventures_hero_clicked"
  | "family_adventure_card_opened"
  | "family_adventure_detail_viewed"
  | "family_adventure_saved"
  | "family_adventure_attended"
  | "family_adventure_attend_clicked"
  | "family_adventure_booking_clicked"
  | "family_adventure_map_opened"
  | "family_adventure_collection_selected"
  | "today_plan_feedback"
  | "premium_feature_used"
  | "feature_request_submitted"
  | "feature_request_voted"
  // Today dashboard
  | "today_dashboard_viewed"
  | "meal_card_opened"
  | "meal_opened"
  | "story_card_opened"
  | "story_opened"
  | "activity_card_opened"
  | "activity_opened"
  | "language_card_opened"
  | "milestone_card_opened"
  | "parent_tip_opened"
  | "today_plan_viewed"
  | "today_refresh_clicked"
  // MumBot
  | "mumbot_opened"
  | "mumbot_question_asked"
  | "mumbot_followup_clicked"
  | "mumbot_story_generated"
  | "mumbot_recipe_generated"
  | "mumbot_activity_generated"
  | "mumbot_feedback_positive"
  | "mumbot_feedback_negative"
  // Stories
  | "story_started"
  | "story_completed"
  | "story_saved"
  | "activity_saved"
  | "story_rotated"
  // Family Voice Storytime
  | "family_story_generated"
  | "family_story_played"
  | "family_story_completed"
  | "family_story_narrated"
  | "family_story_favorited"
  | "voice_profile_created"
  | "voice_profile_ready"
  | "voice_recording_started"
  | "narrator_selected"
  | "bedtime_mode_opened"
  // Visual Routine Studio
  | "routine_created"
  | "routine_started"
  | "routine_completed"
  | "routine_step_skipped"
  // Routine Poster / Adventure Journey
  | "poster_created"
  | "poster_printed"
  | "poster_downloaded"
  | "poster_qr_scanned"
  | "poster_edited"
  // AI Adventure Journey
  | "adventure_generated"
  | "adventure_printed"
  | "adventure_qr_scanned"
  | "adventure_edited"
  | "adventure_deleted"
  | "adventure_completed"
  | "adventure_story_played"
  | "adventure_song_played"
  // AI Toy Brain
  | "toy_brain_scanned"
  | "toy_brain_confirmed"
  | "toy_brain_manual_added"
  | "toy_brain_updated"
  | "toy_brain_deleted"
  | "toy_brain_favourited"
  | "toy_brain_added_to_today"
  | "toy_brain_activity_printed"
  // Meals
  | "meal_viewed"
  | "activity_viewed"
  | "story_viewed"
  | "language_viewed"
  | "meal_saved"
  | "meal_rotated"
  | "meal_from_fridge"
  | "meal_from_fridge_retry"
  // Activities
  | "activity_started"
  | "activity_completed"
  | "activity_rotated"
  // Language
  | "language_activity_started"
  | "language_activity_completed"
  // Connect
  | "available_today_created"
  | "available_today_updated"
  | "available_today_closed"
  | "event_created"
  | "event_updated"
  | "event_join_requested"
  | "event_join_approved"
  | "event_join_declined"
  | "connection_interest_sent"
  | "connection_request_accepted"
  | "connection_request_declined"
  | "connect_page_opened"
  | "connect_opened"
  // Parent check-in
  | "parent_checkin_started"
  | "parent_checkin_completed"
  // Retention
  | "day_1_return"
  | "day_3_return"
  | "day_7_return"
  | "day_30_return"
  | "weekly_active_user"
  | "monthly_active_user"
  // Feature usage (page / section)
  | "feature_used"
  // Feedback & errors
  | "feedback_submitted"
  | "error_occurred"
  | "app_error";

export type FeatureName =
  | "Today"
  | "MumBot"
  | "Connect"
  | "Stories"
  | "Meals"
  | "Activities"
  | "Language"
  | "Milestones"
  | "Parent Check-in"
  | "Profile"
  | "Settings"
  | "Saved"
  | "More"
  | "Stories";

export const PATH_FEATURE_MAP: Record<string, FeatureName> = {
  "/today": "Today",
  "/mumbot": "MumBot",
  "/connect": "Connect",
  "/saved": "Saved",
  "/profile": "Profile",
  "/more": "More",
  "/stories": "Stories",
  "/onboarding": "Settings",
  "/home": "Today",
  "/memory": "Milestones",
  "/activities": "Activities",
  "/chat": "MumBot",
};
