import type { PosterTheme } from "@prisma/client";
import type { PosterThemeStyle } from "@/types/routine-poster";

export const POSTER_THEMES: Record<PosterTheme, PosterThemeStyle> = {
  DINOSAUR: {
    id: "DINOSAUR",
    label: "Dinosaur Adventure",
    emoji: "🦕",
    headline: "Dino Mission",
    background: "#E8F5E9",
    backgroundGradient: "linear-gradient(180deg, #E8F5E9 0%, #C8E6C9 100%)",
    primary: "#2E7D32",
    secondary: "#66BB6A",
    accent: "#FF8F00",
    text: "#1B5E20",
    rewardEmoji: "🦖",
    celebration: "Roarsome job!",
    arrowColor: "#388E3C",
    fontClass: "font-bold",
    isPremium: false,
  },
  FIRE_ENGINE: {
    id: "FIRE_ENGINE",
    label: "Firefighter Mission",
    emoji: "🚒",
    headline: "Firefighter Mission",
    background: "#FFEBEE",
    backgroundGradient: "linear-gradient(180deg, #FFEBEE 0%, #FFCDD2 100%)",
    primary: "#C62828",
    secondary: "#EF5350",
    accent: "#FFC107",
    text: "#B71C1C",
    rewardEmoji: "🏅",
    celebration: "Hero mission complete!",
    arrowColor: "#D32F2F",
    fontClass: "font-bold",
    isPremium: true,
  },
  SPACE: {
    id: "SPACE",
    label: "Space Explorer",
    emoji: "🚀",
    headline: "Space Mission",
    background: "#E8EAF6",
    backgroundGradient: "linear-gradient(180deg, #E8EAF6 0%, #C5CAE9 100%)",
    primary: "#283593",
    secondary: "#5C6BC0",
    accent: "#FFD54F",
    text: "#1A237E",
    rewardEmoji: "🌟",
    celebration: "Blast off — you did it!",
    arrowColor: "#3949AB",
    fontClass: "font-bold",
    isPremium: true,
  },
  PRINCESS: {
    id: "PRINCESS",
    label: "Princess Castle",
    emoji: "👑",
    headline: "Castle Routine",
    background: "#FCE4EC",
    backgroundGradient: "linear-gradient(180deg, #FCE4EC 0%, #F8BBD9 100%)",
    primary: "#AD1457",
    secondary: "#EC407A",
    accent: "#FFD700",
    text: "#880E4F",
    rewardEmoji: "👸",
    celebration: "Royal star!",
    arrowColor: "#C2185B",
    fontClass: "font-bold",
    isPremium: true,
  },
  UNICORN: {
    id: "UNICORN",
    label: "Unicorn Magic",
    emoji: "🦄",
    headline: "Unicorn Magic",
    background: "#F3E5F5",
    backgroundGradient: "linear-gradient(180deg, #F3E5F5 0%, #E1BEE7 100%)",
    primary: "#7B1FA2",
    secondary: "#BA68C8",
    accent: "#FF80AB",
    text: "#4A148C",
    rewardEmoji: "✨",
    celebration: "Magical work!",
    arrowColor: "#8E24AA",
    fontClass: "font-bold",
    isPremium: false,
  },
  ANIMALS: {
    id: "ANIMALS",
    label: "Safari Friends",
    emoji: "🐾",
    headline: "Animal Adventure",
    background: "#FFF8E1",
    backgroundGradient: "linear-gradient(180deg, #FFF8E1 0%, #FFECB3 100%)",
    primary: "#F57F17",
    secondary: "#FFB300",
    accent: "#8D6E63",
    text: "#E65100",
    rewardEmoji: "🐯",
    celebration: "Wildly wonderful!",
    arrowColor: "#FF8F00",
    fontClass: "font-bold",
    isPremium: false,
  },
  CARS: {
    id: "CARS",
    label: "Race Day",
    emoji: "🚗",
    headline: "Race Day Routine",
    background: "#E3F2FD",
    backgroundGradient: "linear-gradient(180deg, #E3F2FD 0%, #BBDEFB 100%)",
    primary: "#1565C0",
    secondary: "#42A5F5",
    accent: "#FF5722",
    text: "#0D47A1",
    rewardEmoji: "🏁",
    celebration: "Finish line champion!",
    arrowColor: "#1976D2",
    fontClass: "font-bold",
    isPremium: true,
  },
  CONSTRUCTION: {
    id: "CONSTRUCTION",
    label: "Builder Zone",
    emoji: "🚧",
    headline: "Builder Mission",
    background: "#FFF3E0",
    backgroundGradient: "linear-gradient(180deg, #FFF3E0 0%, #FFE0B2 100%)",
    primary: "#E65100",
    secondary: "#FF9800",
    accent: "#FFC107",
    text: "#BF360C",
    rewardEmoji: "🏗️",
    celebration: "Build complete!",
    arrowColor: "#F57C00",
    fontClass: "font-bold",
    isPremium: true,
  },
  OCEAN: {
    id: "OCEAN",
    label: "Ocean Adventure",
    emoji: "🐬",
    headline: "Ocean Explorer",
    background: "#E0F7FA",
    backgroundGradient: "linear-gradient(180deg, #E0F7FA 0%, #B2EBF2 100%)",
    primary: "#00838F",
    secondary: "#26C6DA",
    accent: "#FF7043",
    text: "#006064",
    rewardEmoji: "🐠",
    celebration: "Splashing success!",
    arrowColor: "#0097A7",
    fontClass: "font-bold",
    isPremium: true,
  },
  FAIRY: {
    id: "FAIRY",
    label: "Fairy Garden",
    emoji: "🧚",
    headline: "Fairy Garden",
    background: "#E8F5E9",
    backgroundGradient: "linear-gradient(180deg, #F1F8E9 0%, #DCEDC8 100%)",
    primary: "#558B2F",
    secondary: "#9CCC65",
    accent: "#FF4081",
    text: "#33691E",
    rewardEmoji: "🌸",
    celebration: "Fairy-tastic!",
    arrowColor: "#689F38",
    fontClass: "font-bold",
    isPremium: true,
  },
  PIRATE: {
    id: "PIRATE",
    label: "Pirate Treasure Hunt",
    emoji: "🏴‍☠️",
    headline: "Treasure Hunt",
    background: "#EFEBE9",
    backgroundGradient: "linear-gradient(180deg, #EFEBE9 0%, #D7CCC8 100%)",
    primary: "#4E342E",
    secondary: "#8D6E63",
    accent: "#FFD54F",
    text: "#3E2723",
    rewardEmoji: "💎",
    celebration: "Treasure found!",
    arrowColor: "#6D4C41",
    fontClass: "font-bold",
    isPremium: true,
  },
  SAFARI: {
    id: "SAFARI",
    label: "Safari Journey",
    emoji: "🐘",
    headline: "Safari Journey",
    background: "#FFFDE7",
    backgroundGradient: "linear-gradient(180deg, #FFFDE7 0%, #FFF9C4 100%)",
    primary: "#F9A825",
    secondary: "#FFD54F",
    accent: "#795548",
    text: "#F57F17",
    rewardEmoji: "🦁",
    celebration: "Safari star!",
    arrowColor: "#FFB300",
    fontClass: "font-bold",
    isPremium: true,
  },
};

export function getThemeStyle(theme: PosterTheme): PosterThemeStyle {
  return POSTER_THEMES[theme] ?? POSTER_THEMES.DINOSAUR;
}

export function applyColourAccent(style: PosterThemeStyle, colour?: string): PosterThemeStyle {
  if (!colour) return style;
  const map: Record<string, string> = {
    blue: "#3B82F6",
    pink: "#EC4899",
    green: "#22C55E",
    yellow: "#EAB308",
    purple: "#A855F7",
    orange: "#F97316",
  };
  const accent = map[colour];
  return accent ? { ...style, accent } : style;
}
