import type { FamilyAdventure } from "@/lib/family-adventures/types";
import type { AdventureConnector } from "@/lib/family-adventures/connectors/types";
import { resolveBookingLabel, resolveBookingUrl } from "@/lib/family-adventures/booking-link";

type AdventureSeed = Omit<
  FamilyAdventure,
  "id" | "providerId" | "distanceKm" | "travelMinutes" | "bookingUrl" | "bookingLabel"
>;

const BASE_ADVENTURES: AdventureSeed[] = [
  {
    title: "National Museum of Ireland — Natural History",
    description:
      "Meet the famous giraffe and explore Irish wildlife. Perfect for curious minds who love animals and discovery.",
    location: "Merrion Street, Dublin 2",
    area: "Dublin City Centre",
    priceLabel: "Free",
    priceCents: 0,
    ageMinMonths: 24,
    ageMaxMonths: 96,
    ageLabel: "2–8 years",
    durationMinutes: 90,
    category: "museum",
    indoorOutdoor: "indoor",
    imageEmoji: "🦒",
    bookingLink: {
      kind: "direct",
      url: "https://www.museum.ie/en-IE/Museums/National-Museum-of-Ireland-Natural-History",
    },
    openingHours: "Tue–Sun 10:00–17:00",
    whatToBring: ["Snacks", "Light jacket"],
    parking: "Street parking nearby",
    toilets: true,
    babyFacilities: true,
    wheelchairAccess: true,
    rainSuitable: true,
    learningSkills: ["Curiosity", "Language", "Problem solving"],
    followUpActivity: "Draw your favourite animal from the museum",
    interestTags: ["animals", "dinosaur", "nature", "science"],
    isFree: true,
    mapQuery: "National Museum of Ireland Natural History Dublin",
  },
  {
    title: "Dublin Zoo",
    description:
      "A classic family day out with trains, animals, and plenty of space to explore. Great for active toddlers and preschoolers.",
    location: "Phoenix Park, Dublin 8",
    area: "Phoenix Park",
    priceLabel: "From €22",
    priceCents: 2200,
    ageMinMonths: 12,
    ageMaxMonths: 96,
    ageLabel: "All ages",
    durationMinutes: 180,
    category: "zoo",
    indoorOutdoor: "either",
    imageEmoji: "🦁",
    bookingLink: { kind: "direct", url: "https://www.dublinzoo.ie" },
    openingHours: "Daily 9:30–18:00",
    whatToBring: ["Water bottles", "Comfortable shoes", "Rain jacket"],
    parking: "On-site car park",
    toilets: true,
    babyFacilities: true,
    wheelchairAccess: true,
    rainSuitable: false,
    learningSkills: ["Curiosity", "Language", "Social skills"],
    followUpActivity: "Toy Brain: build a zoo with blocks",
    interestTags: ["animals", "trains", "nature"],
    isFree: false,
    mapQuery: "Dublin Zoo",
  },
  {
    title: "Imaginosity — Children's Museum",
    description:
      "Hands-on role-play worlds designed for young children. Ideal for rainy days and imaginative play.",
    location: "The Plaza, Beacon South Quarter, Sandyford",
    area: "South Dublin",
    priceLabel: "From €9",
    priceCents: 900,
    ageMinMonths: 18,
    ageMaxMonths: 96,
    ageLabel: "1.5–8 years",
    durationMinutes: 120,
    category: "indoor_play",
    indoorOutdoor: "indoor",
    imageEmoji: "🎭",
    bookingLink: { kind: "direct", url: "https://www.imaginosity.ie" },
    openingHours: "Tue–Sun, session times vary",
    whatToBring: ["Socks for play areas"],
    parking: "Beacon South Quarter car park",
    toilets: true,
    babyFacilities: true,
    wheelchairAccess: true,
    rainSuitable: true,
    learningSkills: ["Creativity", "Social skills", "Emotional regulation"],
    followUpActivity: "Pretend play café at home",
    interestTags: ["pretend play", "creative", "indoor"],
    isFree: false,
    mapQuery: "Imaginosity Dublin",
  },
  {
    title: "Airfield Estate",
    description:
      "Farm animals, gardens, and gentle walks. A calm outdoor adventure with plenty for little explorers.",
    location: "Overend Avenue, Dundrum, Dublin 14",
    area: "Dundrum",
    priceLabel: "From €12",
    priceCents: 1200,
    ageMinMonths: 12,
    ageMaxMonths: 96,
    ageLabel: "1–8 years",
    durationMinutes: 120,
    category: "farm",
    indoorOutdoor: "outdoor",
    imageEmoji: "🐑",
    bookingLink: { kind: "direct", url: "https://www.airfield.ie" },
    openingHours: "Daily 9:30–17:00",
    whatToBring: ["Wellies if wet", "Picnic"],
    parking: "Free on-site",
    toilets: true,
    babyFacilities: true,
    wheelchairAccess: true,
    rainSuitable: false,
    learningSkills: ["Curiosity", "Physical development", "Language"],
    followUpActivity: "Name three animals you saw today",
    interestTags: ["animals", "nature", "outdoor"],
    isFree: false,
    mapQuery: "Airfield Estate Dundrum",
  },
  {
    title: "Central Library Story Time",
    description:
      "Free weekly story sessions in a welcoming library setting. Perfect for language development and calm mornings.",
    location: "Ilac Centre, Dublin 1",
    area: "Dublin City Centre",
    priceLabel: "Free",
    priceCents: 0,
    ageMinMonths: 18,
    ageMaxMonths: 72,
    ageLabel: "1.5–6 years",
    durationMinutes: 45,
    category: "library",
    indoorOutdoor: "indoor",
    imageEmoji: "📚",
    eventDateLabel: "Library events this week",
    bookingLink: {
      kind: "dublin-city-council",
      eventType: "library-event",
      dateWindow: "week",
      searchQuery: "story",
      label: "Library story events this week",
    },
    openingHours: "Check local library schedule",
    whatToBring: ["Library card optional"],
    parking: "Ilac Centre car park",
    toilets: true,
    babyFacilities: true,
    wheelchairAccess: true,
    rainSuitable: true,
    learningSkills: ["Language", "Listening", "Social skills"],
    followUpActivity: "Create a bedtime story about the library",
    interestTags: ["books", "story", "indoor", "free"],
    isFree: true,
    mapQuery: "Dublin City Library Ilac Centre",
  },
  {
    title: "Phoenix Park Playground",
    description:
      "Spacious playground with climbing frames and open green space. Great when the weather is on your side.",
    location: "Phoenix Park, Dublin 8",
    area: "Phoenix Park",
    priceLabel: "Free",
    priceCents: 0,
    ageMinMonths: 24,
    ageMaxMonths: 96,
    ageLabel: "2–8 years",
    durationMinutes: 60,
    category: "playground",
    indoorOutdoor: "outdoor",
    imageEmoji: "🛝",
    openingHours: "Open daily, daylight hours",
    whatToBring: ["Sunscreen", "Water", "Change of clothes"],
    parking: "Free nearby",
    toilets: true,
    babyFacilities: false,
    wheelchairAccess: true,
    rainSuitable: false,
    learningSkills: ["Physical development", "Social skills", "Confidence"],
    followUpActivity: "Draw the tallest slide you went on",
    interestTags: ["outdoor", "active", "free", "playground"],
    isFree: true,
    mapQuery: "Phoenix Park Playground Dublin",
  },
  {
    title: "St Anne's Park Fairy Trail",
    description:
      "A gentle nature walk with fairy doors hidden among the trees. Magical for imaginative preschoolers.",
    location: "St Anne's Park, Raheny, Dublin 5",
    area: "North Dublin",
    priceLabel: "Free",
    priceCents: 0,
    ageMinMonths: 30,
    ageMaxMonths: 96,
    ageLabel: "2.5–8 years",
    durationMinutes: 75,
    category: "nature",
    indoorOutdoor: "outdoor",
    imageEmoji: "🧚",
    openingHours: "Open daily",
    whatToBring: ["Wellies", "Bug jar optional"],
    parking: "Free car parks in park",
    toilets: true,
    babyFacilities: false,
    wheelchairAccess: false,
    rainSuitable: false,
    learningSkills: ["Curiosity", "Creativity", "Physical development"],
    followUpActivity: "Build a fairy house from leaves",
    interestTags: ["nature", "creative", "outdoor", "free"],
    isFree: true,
    mapQuery: "St Anne's Park Raheny",
  },
  {
    title: "Dublin City Fleadh — Family Festival",
    description:
      "Free traditional music festival across Dublin city centre — Céilís, storytelling, and family activities on Parliament Street and Capel Street.",
    location: "Parliament Street & Capel Street, Dublin",
    area: "Dublin City Centre",
    priceLabel: "Free",
    priceCents: 0,
    ageMinMonths: 0,
    ageMaxMonths: 96,
    ageLabel: "All ages",
    durationMinutes: 180,
    category: "community",
    indoorOutdoor: "outdoor",
    imageEmoji: "🎻",
    eventDateLabel: "Sat 22 – Sun 23 Aug · 12pm–6pm",
    bookingLink: {
      kind: "dublin-city-council",
      eventSlug: "dublin-city-council-dublin-city-fleadh",
      label: "View Dublin City Fleadh details",
    },
    openingHours: "Sat–Sun 12:00–18:00",
    whatToBring: ["Weather-appropriate clothing", "Snacks"],
    parking: "City centre — public transport recommended",
    toilets: true,
    babyFacilities: true,
    wheelchairAccess: true,
    rainSuitable: false,
    learningSkills: ["Social skills", "Creativity", "Language"],
    followUpActivity: "Learn a new Irish word from the festival",
    interestTags: ["community", "festival", "free", "music"],
    isFree: true,
    mapQuery: "Parliament Street Dublin",
  },
  {
    title: "Dublin City Council — Kids & Family Fun",
    description:
      "Browse free council-run family events happening across Dublin in the next week — crafts, play, and community fun.",
    location: "Various venues, Dublin",
    area: "Dublin",
    priceLabel: "Free",
    priceCents: 0,
    ageMinMonths: 0,
    ageMaxMonths: 96,
    ageLabel: "0–8 years",
    durationMinutes: 120,
    category: "community",
    indoorOutdoor: "either",
    imageEmoji: "🎪",
    eventDateLabel: "Events in the next week",
    bookingLink: {
      kind: "dublin-city-council",
      eventType: "kids-family-fun",
      dateWindow: "week",
      label: "Kids & Family Fun · next week",
    },
    openingHours: "Weekends, seasonal",
    whatToBring: ["Weather-appropriate clothing"],
    parking: "Varies by venue",
    toilets: true,
    babyFacilities: true,
    wheelchairAccess: true,
    rainSuitable: true,
    learningSkills: ["Social skills", "Creativity", "Confidence"],
    interestTags: ["community", "festival", "free"],
    isFree: true,
    mapQuery: "Dublin City Council events",
  },
  {
    title: "National Botanic Gardens",
    description:
      "Greenhouses, ponds, and peaceful paths. Wonderful for nature lovers and gentle family strolls.",
    location: "Glasnevin, Dublin 9",
    area: "North Dublin",
    priceLabel: "Free",
    priceCents: 0,
    ageMinMonths: 0,
    ageMaxMonths: 96,
    ageLabel: "All ages",
    durationMinutes: 90,
    category: "nature",
    indoorOutdoor: "either",
    imageEmoji: "🌿",
    bookingLink: { kind: "direct", url: "https://www.botanicgardens.ie" },
    openingHours: "Daily 9:00–17:00",
    whatToBring: ["Camera", "Snacks"],
    parking: "Limited on-site",
    toilets: true,
    babyFacilities: true,
    wheelchairAccess: true,
    rainSuitable: true,
    learningSkills: ["Curiosity", "Language", "Creativity"],
    followUpActivity: "Press flowers or leaf rubbings at home",
    interestTags: ["nature", "outdoor", "science", "free"],
    isFree: true,
    mapQuery: "National Botanic Gardens Glasnevin",
  },
  {
    title: "Train Spotting at Tara Street",
    description:
      "Watch trains pass from a safe viewing spot — perfect for little ones who love locomotives.",
    location: "Tara Street, Dublin 2",
    area: "Dublin City Centre",
    priceLabel: "Free",
    priceCents: 0,
    ageMinMonths: 24,
    ageMaxMonths: 72,
    ageLabel: "2–6 years",
    durationMinutes: 30,
    category: "community",
    indoorOutdoor: "outdoor",
    imageEmoji: "🚂",
    openingHours: "Daylight hours",
    whatToBring: ["Snacks for waiting"],
    parking: "Street parking",
    toilets: false,
    babyFacilities: false,
    wheelchairAccess: true,
    rainSuitable: false,
    learningSkills: ["Language", "Patience", "Curiosity"],
    followUpActivity: "Emotion Train Adventure play at home",
    interestTags: ["trains", "vehicles", "free", "outdoor"],
    isFree: true,
    mapQuery: "Tara Street Station Dublin",
  },
  {
    title: "Eventbrite — Family Workshop",
    description:
      "Curated family-friendly workshops and events happening near you this week.",
    location: "Dublin area",
    area: "Dublin",
    priceLabel: "Varies",
    priceCents: 1500,
    ageMinMonths: 36,
    ageMaxMonths: 96,
    ageLabel: "3–8 years",
    durationMinutes: 60,
    category: "festival",
    indoorOutdoor: "indoor",
    imageEmoji: "🎨",
    eventDateLabel: "Workshops this month",
    bookingLink: {
      kind: "eventbrite",
      url: "https://www.eventbrite.ie/d/ireland--dublin/family/",
      dateWindow: "month",
      searchQuery: "family workshop kids",
      label: "Family workshops on Eventbrite",
    },
    openingHours: "Check event listing",
    whatToBring: ["Booking confirmation"],
    parking: "Varies",
    toilets: true,
    babyFacilities: false,
    wheelchairAccess: true,
    rainSuitable: true,
    learningSkills: ["Creativity", "Social skills", "Confidence"],
    interestTags: ["creative", "indoor", "stem"],
    isFree: false,
    mapQuery: "Dublin family events",
  },
  {
    title: "Rainy Day — Cosy Home Adventure",
    description:
      "When the weather turns, Parenfy suggests Toy Brain play, stories, and indoor missions from Today's Plan.",
    location: "At home",
    area: "Your home",
    priceLabel: "Free",
    priceCents: 0,
    ageMinMonths: 0,
    ageMaxMonths: 96,
    ageLabel: "0–8 years",
    durationMinutes: 45,
    category: "indoor_play",
    indoorOutdoor: "indoor",
    imageEmoji: "🏠",
    openingHours: "Anytime",
    whatToBring: ["Favourite toys"],
    toilets: true,
    babyFacilities: true,
    wheelchairAccess: true,
    rainSuitable: true,
    learningSkills: ["Creativity", "Emotional regulation", "Language"],
    followUpActivity: "Scan a toy with Toy Brain",
    interestTags: ["indoor", "rainy", "free", "toy"],
    isFree: true,
    mapQuery: "",
  },
];

function withDistance(adventure: AdventureSeed, providerId: string, index: number): FamilyAdventure {
  const distanceKm = adventure.location === "At home" ? 0 : 2 + (index % 5) * 2.5;
  const travelMinutes = adventure.location === "At home" ? 0 : Math.round(distanceKm * 3.5);
  const bookingUrl = resolveBookingUrl(adventure.bookingLink);
  const bookingLabel = resolveBookingLabel(adventure.bookingLink, adventure.title);
  return {
    ...adventure,
    id: `${providerId}-${index}`,
    providerId,
    distanceKm: Math.round(distanceKm * 10) / 10,
    travelMinutes,
    bookingUrl,
    bookingLabel,
  };
}

function buildProviderAdventures(providerId: string, filter?: (a: AdventureSeed) => boolean) {
  return BASE_ADVENTURES.filter(filter ?? (() => true)).map((a, i) => withDistance(a, providerId, i));
}

export const seedCatalogConnector: AdventureConnector = {
  id: "parenfy-catalog",
  name: "Parenfy Curated",
  fetchAdventures: async () => buildProviderAdventures("parenfy-catalog"),
};

export const dublinCityConnector: AdventureConnector = {
  id: "dublin-city-council",
  name: "Dublin City Council",
  fetchAdventures: async () =>
    buildProviderAdventures("dublin-city-council", (a) => a.category === "community" || a.isFree),
};

export const libraryConnector: AdventureConnector = {
  id: "local-libraries",
  name: "Local Libraries",
  fetchAdventures: async () => buildProviderAdventures("local-libraries", (a) => a.category === "library"),
};

export const museumConnector: AdventureConnector = {
  id: "national-museum",
  name: "National Museum",
  fetchAdventures: async () => buildProviderAdventures("national-museum", (a) => a.category === "museum"),
};

export const zooConnector: AdventureConnector = {
  id: "dublin-zoo",
  name: "Dublin Zoo",
  fetchAdventures: async () => buildProviderAdventures("dublin-zoo", (a) => a.category === "zoo"),
};

export const playgroundConnector: AdventureConnector = {
  id: "playground-db",
  name: "Playground Database",
  fetchAdventures: async () =>
    buildProviderAdventures("playground-db", (a) => a.category === "playground" || a.category === "nature"),
};

export const eventbriteConnector: AdventureConnector = {
  id: "eventbrite",
  name: "Eventbrite",
  fetchAdventures: async () => buildProviderAdventures("eventbrite", (a) => a.category === "festival"),
};

export const imaginosityConnector: AdventureConnector = {
  id: "imaginosity",
  name: "Imaginosity",
  fetchAdventures: async () => buildProviderAdventures("imaginosity", (a) => a.category === "indoor_play"),
};

export const airfieldConnector: AdventureConnector = {
  id: "airfield-estate",
  name: "Airfield Estate",
  fetchAdventures: async () => buildProviderAdventures("airfield-estate", (a) => a.category === "farm"),
};
