import { KnowledgeArticleCategory, KnowledgeTipCategory } from "@prisma/client";

export const extraRecipes = [
  { subtitle: "Scrambled Egg Muffins", prepTimeMinutes: 18, ingredients: ["Eggs", "Spinach", "Cheese", "Milk"], tags: ["breakfast", "protein"] },
  { subtitle: "Sweet Potato Mash", prepTimeMinutes: 25, ingredients: ["Sweet potato", "Butter", "Cinnamon"], tags: ["vegetarian", "comfort"] },
  { subtitle: "Chicken & Veg Soup", prepTimeMinutes: 35, ingredients: ["Chicken", "Carrot", "Celery", "Noodles"], tags: ["warm", "protein"] },
  { subtitle: "Fruit & Yogurt Smoothie Bowl", prepTimeMinutes: 8, ingredients: ["Yogurt", "Banana", "Berries", "Granola"], tags: ["breakfast", "fruit"] },
  { subtitle: "Cheese & Tomato Quesadilla", prepTimeMinutes: 10, ingredients: ["Tortilla", "Cheese", "Tomato"], tags: ["quick", "lunch"] },
  { subtitle: "Mini Meatballs & Pasta", prepTimeMinutes: 30, ingredients: ["Beef mince", "Pasta", "Tomato sauce"], tags: ["protein", "pasta"] },
  { subtitle: "Cottage Cheese Pancakes", prepTimeMinutes: 15, ingredients: ["Cottage cheese", "Flour", "Egg", "Honey"], tags: ["breakfast"] },
  { subtitle: "Broccoli & Cheese Bake", prepTimeMinutes: 28, ingredients: ["Broccoli", "Cheese", "Milk", "Breadcrumbs"], tags: ["vegetarian"] },
  { subtitle: "Tuna Pasta Salad", prepTimeMinutes: 15, ingredients: ["Pasta", "Tuna", "Sweetcorn", "Mayo"], tags: ["quick", "fish"] },
  { subtitle: "Apple Cinnamon Oatmeal", prepTimeMinutes: 12, ingredients: ["Oats", "Apple", "Cinnamon", "Milk"], tags: ["breakfast", "warm"] },
  { subtitle: "Veggie Fried Rice", prepTimeMinutes: 20, ingredients: ["Rice", "Peas", "Carrot", "Egg"], tags: ["quick", "vegetarian"] },
  { subtitle: "Peanut Butter Banana Wrap", prepTimeMinutes: 5, ingredients: ["Wrap", "Peanut butter", "Banana"], tags: ["quick", "snack"] },
  { subtitle: "Baked Salmon Fingers", prepTimeMinutes: 22, ingredients: ["Salmon", "Breadcrumbs", "Lemon"], tags: ["fish", "protein"] },
  { subtitle: "Mushroom & Cheese Toast", prepTimeMinutes: 12, ingredients: ["Bread", "Mushrooms", "Cheese"], tags: ["quick", "vegetarian"] },
  { subtitle: "Carrot & Lentil Dhal", prepTimeMinutes: 30, ingredients: ["Red lentils", "Carrot", "Coconut milk", "Rice"], tags: ["vegetarian", "iron"] },
  { subtitle: "Egg Fried Noodles", prepTimeMinutes: 15, ingredients: ["Noodles", "Egg", "Soy sauce", "Peas"], tags: ["quick"] },
  { subtitle: "Stuffed Bell Peppers", prepTimeMinutes: 35, ingredients: ["Bell pepper", "Rice", "Mince", "Tomato"], tags: ["dinner"] },
  { subtitle: "Berry Chia Pudding", prepTimeMinutes: 5, ingredients: ["Chia seeds", "Milk", "Berries", "Honey"], tags: ["breakfast", "no-cook"] },
  { subtitle: "Chicken & Sweetcorn Fritters", prepTimeMinutes: 20, ingredients: ["Chicken", "Sweetcorn", "Flour", "Egg"], tags: ["finger-food"] },
  { subtitle: "Tomato & Basil Soup", prepTimeMinutes: 25, ingredients: ["Tomatoes", "Basil", "Stock", "Bread"], tags: ["warm", "vegetarian"] },
  { subtitle: "Cheesy Potato Skins", prepTimeMinutes: 30, ingredients: ["Potato", "Cheese", "Spring onion"], tags: ["comfort"] },
  { subtitle: "Fruit Skewers & Dip", prepTimeMinutes: 10, ingredients: ["Melon", "Grapes", "Strawberries", "Yogurt"], tags: ["snack", "fruit"] },
  { subtitle: "Beef & Bean Tacos", prepTimeMinutes: 25, ingredients: ["Tortilla", "Beef", "Black beans", "Cheese"], tags: ["dinner"] },
  { subtitle: "Spinach & Ricotta Rolls", prepTimeMinutes: 28, ingredients: ["Puff pastry", "Spinach", "Ricotta"], tags: ["vegetarian"] },
  { subtitle: "Honey Mustard Chicken Wraps", prepTimeMinutes: 18, ingredients: ["Chicken", "Wrap", "Honey", "Mustard"], tags: ["lunch"] },
].map((r) => ({
  slug: r.subtitle.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 80),
  title: "Today's Healthy Lunch",
  subtitle: r.subtitle,
  minAgeMonths: 12,
  maxAgeMonths: 72,
  prepTimeMinutes: r.prepTimeMinutes,
  ingredients: r.ingredients,
  steps: ["Prepare ingredients.", "Cook and combine.", "Serve at safe temperature."],
  detailedSteps: [
    "Gather and prep all ingredients.",
    "Follow age-appropriate cooking steps.",
    "Check temperature before serving.",
    "Let your child help with safe tasks.",
  ],
  nutritionTags: ["Balanced"],
  whyThisMeal: `Recommended because ${r.subtitle.toLowerCase()} is balanced and family-friendly.`,
  tags: r.tags,
}));

export const extraActivities = [
  { title: "Bubble Wrap Stomp", durationMinutes: 10, indoorOutdoor: "indoor", skills: ["Sensory", "Gross motor"] },
  { title: "Sock Puppet Show", durationMinutes: 20, indoorOutdoor: "indoor", skills: ["Language", "Creativity"] },
  { title: "Leaf Rubbing Art", durationMinutes: 25, indoorOutdoor: "outdoor", skills: ["Fine motor", "Nature"] },
  { title: "Number Hopscotch", durationMinutes: 15, indoorOutdoor: "either", skills: ["Counting", "Balance"] },
  { title: "Mirror Emotions Game", durationMinutes: 10, indoorOutdoor: "indoor", skills: ["Emotional", "Language"] },
  { title: "Build a Block Tower", durationMinutes: 20, indoorOutdoor: "indoor", skills: ["Fine motor", "Planning"] },
  { title: "Outdoor Chalk Drawing", durationMinutes: 30, indoorOutdoor: "outdoor", skills: ["Creativity", "Gross motor"] },
  { title: "Sorting Laundry Colors", durationMinutes: 15, indoorOutdoor: "indoor", skills: ["Sorting", "Life skills"] },
  { title: "Musical Statues", durationMinutes: 15, indoorOutdoor: "either", skills: ["Listening", "Self-control"] },
  { title: "Puzzle Race", durationMinutes: 20, indoorOutdoor: "indoor", skills: ["Problem solving", "Patience"] },
  { title: "Nature Scavenger Hunt", durationMinutes: 30, indoorOutdoor: "outdoor", skills: ["Observation", "Language"] },
  { title: "Playdough Letter Shapes", durationMinutes: 20, indoorOutdoor: "indoor", skills: ["Fine motor", "Literacy"] },
  { title: "Balloon Volleyball", durationMinutes: 15, indoorOutdoor: "indoor", skills: ["Coordination", "Gross motor"] },
  { title: "Story Dice Game", durationMinutes: 25, indoorOutdoor: "indoor", skills: ["Storytelling", "Creativity"] },
  { title: "Garden Watering Helper", durationMinutes: 15, indoorOutdoor: "outdoor", skills: ["Responsibility", "Nature"] },
].map((a) => ({
  slug: a.title.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
  title: a.title,
  minAgeMonths: 24,
  maxAgeMonths: 72,
  indoorOutdoor: a.indoorOutdoor,
  rainyDay: a.indoorOutdoor !== "outdoor",
  sunnyDay: a.indoorOutdoor !== "indoor",
  durationMinutes: a.durationMinutes,
  materials: ["Household items"],
  instructions: ["Set up the activity.", "Play together.", "Celebrate effort."],
  detailedInstructions: ["Prepare materials.", "Demonstrate once.", "Let your child lead.", "Wrap up together."],
  skillsDeveloped: a.skills,
  tags: ["play", a.indoorOutdoor],
  reason: `Recommended because ${a.title.toLowerCase()} builds skills through fun.`,
}));

export const extraTips = [
  { category: KnowledgeTipCategory.SLEEP, title: "Dim lights 30 minutes before bed", content: "Lowering light signals melatonin release.", tryToday: "Use a lamp instead of overhead light after bath." },
  { category: KnowledgeTipCategory.EATING, title: "Serve new foods alongside favourites", content: "Neutral exposure without pressure helps acceptance.", tryToday: "Add one new vegetable next to a trusted carb." },
  { category: KnowledgeTipCategory.BEHAVIOUR, title: "Name the feeling before fixing", content: "Validation often calms more than immediate correction.", tryToday: "Say 'You seem frustrated' before offering help." },
  { category: KnowledgeTipCategory.EMOTIONAL, title: "Co-regulate with calm voice", content: "Children mirror adult nervous systems.", tryToday: "Take one slow breath before responding to a meltdown." },
  { category: KnowledgeTipCategory.POTTY, title: "Celebrate attempts, not just success", content: "Positive association speeds learning.", tryToday: "Cheer for sitting on the potty, even without result." },
  { category: KnowledgeTipCategory.GENERAL, title: "Prep clothes the night before", content: "Fewer morning decisions reduce stress for everyone.", tryToday: "Lay out tomorrow's outfit with your child." },
  { category: KnowledgeTipCategory.SLEEP, title: "Keep wake time consistent", content: "Regular wake times anchor the sleep rhythm.", tryToday: "Wake within 30 minutes of the same time daily." },
  { category: KnowledgeTipCategory.SPEECH, title: "Repeat and expand their words", content: "Expansions model richer language naturally.", tryToday: "If they say 'truck', reply 'Yes, a big red truck!'" },
  { category: KnowledgeTipCategory.EATING, title: "Eat together when possible", content: "Shared meals model chewing and conversation.", tryToday: "Sit at the table for one meal without screens." },
  { category: KnowledgeTipCategory.EMOTIONAL, title: "Create a calm-down corner", content: "A safe space teaches self-soothing.", tryToday: "Add a cushion, book, and soft toy to a quiet spot." },
].map((t, i) => ({
  slug: `tip-extra-${i + 1}`,
  minAgeMonths: 12,
  maxAgeMonths: 72,
  ...t,
  tags: [t.category.toLowerCase()],
}));

export const extraMilestones = [
  { category: "Motor", title: "Runs with coordination", description: "Many toddlers begin running smoothly without frequent falls.", minAgeMonths: 24, maxAgeMonths: 36 },
  { category: "Speech", title: "Uses 50+ words", description: "Vocabulary often expands rapidly in the second year.", minAgeMonths: 18, maxAgeMonths: 30 },
  { category: "Social", title: "Parallel play with peers", description: "Playing alongside others before playing together.", minAgeMonths: 24, maxAgeMonths: 48 },
  { category: "Cognitive", title: "Sorts by colour or shape", description: "Classification skills emerge through play.", minAgeMonths: 30, maxAgeMonths: 48 },
  { category: "Emotional", title: "Shows empathy", description: "May comfort a crying friend or doll.", minAgeMonths: 36, maxAgeMonths: 60 },
  { category: "Motor", title: "Jumps with both feet", description: "Both feet leave the ground together.", minAgeMonths: 30, maxAgeMonths: 48 },
  { category: "Speech", title: "Asks 'why' questions", description: "Curiosity drives language complexity.", minAgeMonths: 36, maxAgeMonths: 60 },
  { category: "Self-care", title: "Feeds self with spoon", description: "Improving hand-to-mouth coordination.", minAgeMonths: 18, maxAgeMonths: 30 },
  { category: "Social", title: "Takes turns in games", description: "Turn-taking shows growing social awareness.", minAgeMonths: 36, maxAgeMonths: 60 },
  { category: "Cognitive", title: "Completes 6-piece puzzles", description: "Spatial reasoning develops through puzzles.", minAgeMonths: 36, maxAgeMonths: 54 },
  { category: "Motor", title: "Draws circles", description: "Circular scribbles precede recognizable shapes.", minAgeMonths: 36, maxAgeMonths: 48 },
  { category: "Speech", title: "Tells simple stories", description: "Links events: 'We went park and saw dog.'", minAgeMonths: 42, maxAgeMonths: 60 },
  { category: "Emotional", title: "Uses words for feelings", description: "May say 'I sad' or 'I cross' instead of only crying.", minAgeMonths: 30, maxAgeMonths: 48 },
  { category: "Self-care", title: "Helps dress self", description: "Pulls on pants or pushes arms through sleeves.", minAgeMonths: 30, maxAgeMonths: 48 },
  { category: "Cognitive", title: "Understands counting to three", description: "Rote counting may appear before true quantity understanding.", minAgeMonths: 36, maxAgeMonths: 54 },
].map((m, i) => ({
  slug: `milestone-${slugify(m.title)}`,
  maxAgeMonths: m.maxAgeMonths,
  minAgeMonths: m.minAgeMonths,
  category: m.category,
  title: m.title,
  description: m.description,
  whyItMatters: "Tracking milestones helps you celebrate progress, not compare.",
  parentTip: "Offer opportunities to practice without pressure.",
  tags: [m.category.toLowerCase()],
}));

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 60);
}

export const extraBooks = [
  { title: "Dear Zoo", author: "Rod Campbell", theme: "Animals", summary: "Lift-the-flap book about finding the perfect pet." },
  { title: "Guess How Much I Love You", author: "Sam McBratney", theme: "Love", summary: "A tender tale of love between Big and Little Nutbrown Hare." },
  { title: "We're Going on a Bear Hunt", author: "Michael Rosen", theme: "Adventure", summary: "Rhythmic journey through grass, river, and mud." },
  { title: "The Gruffalo", author: "Julia Donaldson", theme: "Courage", summary: "Clever mouse outwits forest creatures." },
  { title: "Goodnight Moon", author: "Margaret Wise Brown", theme: "Bedtime", summary: "Calming bedtime ritual in a great green room." },
  { title: "Brown Bear, Brown Bear", author: "Bill Martin Jr.", theme: "Colours", summary: "Repetitive colour and animal recognition." },
  { title: "Each Peach Pear Plum", author: "Janet and Allan Ahlberg", theme: "Rhyme", summary: "I-spy rhymes with familiar fairy tale characters." },
  { title: "Peepo!", author: "Janet and Allan Ahlberg", theme: "Daily life", summary: "Baby's view of family life in wartime Britain." },
  { title: "Room on the Broom", author: "Julia Donaldson", theme: "Friendship", summary: "Kind witch and animal friends share a broom." },
  { title: "The Tiger Who Came to Tea", author: "Judith Kerr", theme: "Imagination", summary: "Unexpected guest eats everything in the house." },
  { title: "Stick Man", author: "Julia Donaldson", theme: "Family", summary: "Stick man's journey home to his family tree." },
  { title: "Elmer", author: "David McKee", theme: "Self-acceptance", summary: "Patchwork elephant celebrates being different." },
  { title: "The Snail and the Whale", author: "Julia Donaldson", theme: "Adventure", summary: "Tiny snail travels the world on a whale's tail." },
  { title: "Owl Babies", author: "Martin Waddell", theme: "Separation", summary: "Three owlets wait for Mummy Owl to return." },
  { title: "Handa's Surprise", author: "Eileen Browne", theme: "Animals", summary: "Fruit basket adventure with a surprise ending." },
].map((b) => ({
  slug: slugify(b.title),
  minAgeMonths: 12,
  maxAgeMonths: 72,
  language: "English",
  ...b,
  tags: ["classic", b.theme.toLowerCase()],
}));

export const extraSongs = [
  { title: "Twinkle Twinkle Little Star", category: "Lullaby", lyrics: "Twinkle twinkle little star..." },
  { title: "Wheels on the Bus", category: "Action", lyrics: "The wheels on the bus go round and round..." },
  { title: "If You're Happy and You Know It", category: "Action", lyrics: "If you're happy and you know it, clap your hands..." },
  { title: "Head Shoulders Knees and Toes", category: "Body", lyrics: "Head, shoulders, knees and toes..." },
  { title: "Old MacDonald Had a Farm", category: "Animals", lyrics: "Old MacDonald had a farm, E-I-E-I-O..." },
  { title: "Row Row Row Your Boat", category: "Action", lyrics: "Row row row your boat, gently down the stream..." },
  { title: "Incy Wincy Spider", category: "Action", lyrics: "Incy wincy spider climbed up the water spout..." },
  { title: "Baa Baa Black Sheep", category: "Nursery", lyrics: "Baa baa black sheep, have you any wool?" },
  { title: "Five Little Ducks", category: "Counting", lyrics: "Five little ducks went out one day..." },
  { title: "Sleeping Bunnies", category: "Action", lyrics: "See the little bunnies sleeping till it's nearly noon..." },
].map((s) => ({
  slug: slugify(s.title),
  minAgeMonths: 12,
  maxAgeMonths: 60,
  ...s,
  tags: [s.category.toLowerCase()],
}));

export const extraGames = [
  { title: "Simon Says", description: "Follow instructions only when Simon says.", howToPlay: ["One leader gives commands.", "Copy only if 'Simon says' first.", "Swap leaders each round."], indoor: true, outdoor: true },
  { title: "I Spy", description: "Guess an object by its first letter or colour.", howToPlay: ["Say 'I spy with my little eye...'", "Give a clue.", "Take turns guessing."], indoor: true, outdoor: true },
  { title: "Red Light Green Light", description: "Move on green, freeze on red.", howToPlay: ["Leader calls colours.", "Move or stop.", "First to tag leader wins."], indoor: false, outdoor: true },
  { title: "Memory Match", description: "Find matching pairs of cards.", howToPlay: ["Lay cards face down.", "Flip two at a time.", "Keep pairs you match."], indoor: true, outdoor: false },
  { title: "Hot and Cold", description: "Find a hidden object using temperature clues.", howToPlay: ["Hide a toy.", "Say hotter/colder as they search.", "Celebrate when found."], indoor: true, outdoor: true },
  { title: "Animal Charades", description: "Act out animals without speaking.", howToPlay: ["Pick an animal.", "Act it out.", "Others guess."], indoor: true, outdoor: false },
  { title: "Follow the Leader", description: "Copy the leader's movements.", howToPlay: ["Leader walks and moves.", "Others copy exactly.", "Swap leaders."], indoor: true, outdoor: true },
  { title: "What's Missing?", description: "Memory game with household objects.", howToPlay: ["Lay out 5 items.", "Cover and remove one.", "Guess what's missing."], indoor: true, outdoor: false },
  { title: "Obstacle Course Race", description: "Timed course with simple challenges.", howToPlay: ["Set up stations.", "Run the course.", "Beat your best time."], indoor: true, outdoor: true },
  { title: "Story Chain", description: "Build a story one sentence at a time.", howToPlay: ["Start a sentence.", "Each person adds one.", "Record the silly result."], indoor: true, outdoor: false },
].map((g) => ({
  slug: slugify(g.title),
  title: g.title,
  minAgeMonths: 36,
  maxAgeMonths: 72,
  indoor: g.indoor,
  outdoor: g.outdoor,
  solo: false,
  parentChild: true,
  description: g.description,
  howToPlay: g.howToPlay,
  tags: ["game"],
}));

export const weeklyThemes = [
  { slug: "building-connection", title: "Building Connection", domain: "Family", reason: "Small moments of presence and play strengthen your bond this week.", tags: ["connection"] },
  { title: "Emotional Regulation", domain: "Emotional", reason: "Naming feelings and calm-down strategies help children handle big emotions.", tags: ["emotional"] },
  { title: "Language Explosion", domain: "Speech", reason: "Rich conversation and books accelerate vocabulary this week.", tags: ["speech"] },
  { title: "Independent Play", domain: "Independence", reason: "Short solo play builds confidence and gives you breathing room.", tags: ["independence"] },
  { title: "Healthy Eating Habits", domain: "Nutrition", reason: "Neutral exposure and family meals support long-term acceptance.", tags: ["eating"] },
  { title: "Sleep Routine Reset", domain: "Sleep", reason: "Consistent cues anchor better rest for the whole family.", tags: ["sleep"] },
  { title: "Gross Motor Skills", domain: "Physical", reason: "Running, jumping, and climbing strengthen growing bodies.", tags: ["motor"] },
  { title: "Fine Motor Practice", domain: "Physical", reason: "Drawing, threading, and building prepare hands for writing.", tags: ["motor"] },
  { title: "Social Skills & Sharing", domain: "Social", reason: "Turn-taking games build cooperation with siblings and friends.", tags: ["social"] },
  { title: "Outdoor Exploration", domain: "Nature", reason: "Fresh air and nature spark curiosity and calm busy minds.", tags: ["outdoor"] },
  { title: "Creative Expression", domain: "Creativity", reason: "Art and music let children express what words cannot yet.", tags: ["creativity"] },
  { title: "Building Confidence", domain: "Emotional", reason: "Celebrating small wins helps children feel capable.", tags: ["confidence"] },
  { title: "Potty Training Support", domain: "Self-care", reason: "Positive, pressure-free practice builds toileting skills.", tags: ["potty"] },
  { title: "Sibling Connection", domain: "Family", reason: "Shared activities reduce rivalry and build bonds.", tags: ["family"] },
  { title: "Screen Balance", domain: "Routine", reason: "Intentional screen time preserves space for play and connection.", tags: ["routine"] },
  { title: "Mindful Mornings", domain: "Routine", reason: "Predictable starts reduce meltdowns and rush stress.", tags: ["routine"] },
  { title: "Kindness & Empathy", domain: "Social", reason: "Modeling care teaches children to notice others' feelings.", tags: ["empathy"] },
  { title: "Counting & Numbers", domain: "Cognitive", reason: "Everyday counting in play lays maths foundations.", tags: ["math"] },
  { title: "Storytelling Together", domain: "Language", reason: "Shared stories strengthen language and bedtime connection.", tags: ["literacy"] },
  { title: "Sensory Play", domain: "Development", reason: "Textures and mess calm or energize depending on your child's needs.", tags: ["sensory"] },
  { title: "Parent Self-Care", domain: "Family", reason: "Your wellbeing fuels patience — small resets matter.", tags: ["parent"] },
  { title: "Transition Skills", domain: "Behaviour", reason: "Warnings and routines make leaving and changing activities easier.", tags: ["behaviour"] },
  { title: "Water Confidence", domain: "Physical", reason: "Bath and pool play build comfort with water safely.", tags: ["water"] },
  { title: "Music & Rhythm", domain: "Creativity", reason: "Songs and clapping support memory and coordination.", tags: ["music"] },
  { title: "Problem Solving", domain: "Cognitive", reason: "Puzzles and open-ended play teach persistence.", tags: ["cognitive"] },
  { title: "Gratitude Moments", domain: "Emotional", reason: "Naming three good things builds optimism over time.", tags: ["gratitude"] },
].map((w) => ({
  slug: "slug" in w && w.slug ? w.slug : slugify(w.title),
  minAgeMonths: 12,
  maxAgeMonths: 72,
  title: w.title,
  domain: w.domain,
  reason: w.reason,
  tags: w.tags,
}));

export const seedFaqs = [
  { question: "What is Parenfy?", answer: "Parenfy is an AI co-parent that delivers personalised daily plans — meals, activities, stories, and tips — based on your child's age, interests, and goals.", category: "General" },
  { question: "How is content personalised?", answer: "We select from a curated knowledge base matched to your profile, then use AI only to personalise greetings and focus — not to invent recipes or activities from scratch.", category: "Product" },
  { question: "Is Parenfy a medical service?", answer: "No. Parenfy offers general parenting guidance, not medical diagnosis or treatment. Always consult your GP or health visitor for health concerns.", category: "Safety" },
  { question: "What is included in the free plan?", answer: "Free accounts get one personalised daily plan per day, three MumBot chats per day, and 20 AI generations per month.", category: "Billing" },
  { question: "How do Premium and Family differ?", answer: "Premium removes daily limits for one account. Family adds unlimited access for up to four child profiles under one subscription.", category: "Billing" },
  { question: "Can I change my child's profile?", answer: "Yes — update age, interests, and goals in Profile settings. Today's Plan refreshes to match.", category: "Account" },
  { question: "How does Try another work?", answer: "Try another pulls the next option from our knowledge database, ranked for your child's profile — no waiting for AI generation.", category: "Product" },
  { question: "How is my data stored?", answer: "Your account data is stored securely. We do not sell personal information. See our privacy policy for details.", category: "Privacy" },
].map((f, i) => ({
  slug: slugify(f.question),
  sortOrder: i,
  published: true,
  ...f,
}));

export const seedArticles = [
  { title: "Understanding Developmental Milestones", category: KnowledgeArticleCategory.DEVELOPMENT, summary: "What milestones mean — and what they don't.", body: "Developmental milestones are signposts, not deadlines. Children reach skills at different ages...\n\nFocus on progress over comparison. If you have concerns, speak with your health visitor." },
  { title: "Picky Eating: A Gentle Approach", category: KnowledgeArticleCategory.HEALTH, summary: "How to offer new foods without battles.", body: "Picky eating is common. Repeated neutral exposure, family meals, and zero pressure work better than forcing bites...\n\nKeep offering alongside safe favourites." },
  { title: "Bedtime Routines That Work", category: KnowledgeArticleCategory.GUIDE, summary: "Building predictable sleep cues.", body: "A consistent sequence — bath, book, bed — signals the body to wind down...\n\nDim lights 30 minutes before sleep." },
  { title: "Supporting Early Language", category: KnowledgeArticleCategory.DEVELOPMENT, summary: "Everyday strategies for speech growth.", body: "Talk during routines, expand your child's words, read daily, and leave pauses for them to respond...\n\nGestures count as communication too." },
  { title: "Managing Tantrums with Calm", category: KnowledgeArticleCategory.GUIDE, summary: "Co-regulation strategies for big feelings.", body: "Tantrums are normal. Name the feeling, stay nearby, and wait for the storm to pass...\n\nRepair with connection afterward." },
  { title: "Screen Time in Balance", category: KnowledgeArticleCategory.GENERAL, summary: "Practical boundaries without guilt.", body: "Co-view when possible, choose quality content, and protect sleep and meal times...\n\nOutdoor play balances sedentary time." },
  { title: "Preparing for Nursery or School", category: KnowledgeArticleCategory.GUIDE, summary: "Emotional readiness tips.", body: "Visit the setting, read stories about starting, and practice short separations...\n\nValidate worries — they are normal." },
  { title: "Sibling Rivalry: Connection First", category: KnowledgeArticleCategory.GENERAL, summary: "Reducing conflict through one-on-one time.", body: "Special time with each child, fair turns, and avoiding comparisons reduce rivalry...\n\nCelebrate teamwork when you see it." },
].map((a, i) => ({
  slug: slugify(a.title),
  minAgeMonths: 0,
  maxAgeMonths: 216,
  published: true,
  sortOrder: i,
  tags: [a.category.toLowerCase()],
  ...a,
}));
