import type { DailyBriefDevelopment, DailyBriefPlay, DailyBriefRecipe, DailyBriefStory } from "@/types/daily-brief";
import type { BriefProfile } from "@/lib/daily-brief-context";

export const RECIPE_ALTERNATES: Omit<DailyBriefRecipe, "imageData" | "sampleLinks" | "fromFridge">[] = [
  {
    title: "Today's Healthy Lunch",
    subtitle: "Cheesy Rice & Pea Bowl",
    prepTimeMinutes: 15,
    whyThisMeal: "Recommended because soft rice and cheese are comforting, and peas add a gentle pop of colour and nutrients.",
    ingredients: ["Cooked rice", "Peas", "Grated cheese", "Butter", "Splash of milk"],
    steps: ["Warm rice with milk and butter.", "Stir in peas until heated through.", "Top with cheese and serve warm."],
    detailedSteps: [
      "Measure cooked rice into a small pan — leftover rice works well.",
      "Add a splash of milk and a small knob of butter over low heat.",
      "Stir gently until creamy; add more milk if it looks dry.",
      "Add frozen or fresh peas and stir until warmed through.",
      "Remove from heat and sprinkle grated cheese on top.",
      "Let your child stir the cheese in with a spoon.",
      "Check temperature on the inside before serving.",
      "Serve in a shallow bowl for easy scooping.",
    ],
    healthyTip: "Let your child stir the cheese in — involvement often helps acceptance.",
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Mini Veggie Frittata Cups",
    prepTimeMinutes: 22,
    whyThisMeal: "Recommended because protein-rich egg cups are easy to hold and work well for lunch or a snack.",
    ingredients: ["Eggs", "Spinach", "Cherry tomatoes", "Grated cheese", "Olive oil"],
    steps: ["Whisk eggs with a pinch of salt.", "Fold in chopped veg and cheese.", "Bake in oiled muffin tins at 180°C until set."],
    healthyTip: "Serve one cup plain first before adding anything new on the side.",
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Roasted Sweet Potato Wedges",
    prepTimeMinutes: 28,
    whyThisMeal: "Recommended because naturally sweet wedges feel like a treat while offering fibre and energy.",
    ingredients: ["Sweet potato", "Olive oil", "Paprika", "Greek yogurt dip"],
    steps: ["Cut sweet potato into wedges.", "Toss with oil and paprika.", "Roast until soft inside and golden outside.", "Serve with yogurt dip."],
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Avocado & Egg Toast Fingers",
    prepTimeMinutes: 12,
    whyThisMeal: "Recommended because finger-shaped toast supports self-feeding and combines healthy fats with protein.",
    ingredients: ["Wholegrain bread", "Ripe avocado", "Boiled egg", "Lemon juice"],
    steps: ["Toast bread and cut into fingers.", "Mash avocado with lemon.", "Top with sliced egg and serve."],
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Berry & Yogurt Parfait",
    prepTimeMinutes: 8,
    whyThisMeal: "Recommended because layered colours make healthy food feel special without added sugar overload.",
    ingredients: ["Greek yogurt", "Mixed berries", "Granola", "Drizzle of honey"],
    steps: ["Layer yogurt and berries in a clear cup.", "Sprinkle granola on top.", "Serve immediately while crunchy."],
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Turkey & Cheese Roll-Ups",
    prepTimeMinutes: 10,
    whyThisMeal: "Recommended because roll-ups are fun to unroll and pack protein for active afternoons.",
    ingredients: ["Soft tortilla or flatbread", "Sliced turkey", "Cheese slice", "Cucumber sticks"],
    steps: ["Lay turkey and cheese on the wrap.", "Roll tightly and slice into pinwheels.", "Serve with cucumber on the side."],
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Creamy Tomato Pasta",
    prepTimeMinutes: 18,
    whyThisMeal: "Recommended because a mild tomato sauce on familiar pasta is an easy win for many children.",
    ingredients: ["Small pasta shapes", "Passata", "Cream cheese", "Grated parmesan", "Basil"],
    steps: ["Cook pasta until soft.", "Warm passata with cream cheese.", "Toss together and sprinkle basil."],
    healthyTip: "Blend the sauce smooth if your child prefers no lumps.",
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Banana Oat Pancake Bites",
    prepTimeMinutes: 15,
    whyThisMeal: "Recommended because mini pancakes feel like a treat but are made with wholesome oats and fruit.",
    ingredients: ["Ripe banana", "Oats", "Egg", "Cinnamon", "Butter for pan"],
    steps: ["Mash banana and mix with oats and egg.", "Cook spoonfuls in a buttered pan.", "Flip once and serve warm."],
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Veggie Fried Rice",
    prepTimeMinutes: 20,
    whyThisMeal: "Recommended because finely diced vegetables disappear into familiar rice for an easy balanced meal.",
    ingredients: ["Cooked rice", "Frozen peas and corn", "Grated carrot", "Soy sauce", "Egg"],
    steps: ["Scramble egg and set aside.", "Stir-fry veg in a little oil.", "Add rice, soy sauce, and egg.", "Serve warm."],
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Hummus & Veggie Dippers",
    prepTimeMinutes: 10,
    whyThisMeal: "Recommended because dipping builds fine motor skills and makes raw vegetables more appealing.",
    ingredients: ["Hummus", "Carrot sticks", "Cucumber", "Pita strips", "Cherry tomatoes"],
    steps: ["Arrange veg and pita on a plate.", "Scoop hummus into a small bowl.", "Show your child how to dip and crunch."],
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Salmon & Sweetcorn Fish Cakes",
    prepTimeMinutes: 25,
    whyThisMeal: "Recommended because flaky fish in soft cakes is a gentle way to introduce omega-3s.",
    ingredients: ["Canned salmon", "Mashed potato", "Sweetcorn", "Egg", "Breadcrumbs"],
    steps: ["Mix salmon, potato, corn, and egg.", "Shape into small patties and coat lightly.", "Pan-fry until golden both sides."],
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Apple & Cheddar Quesadilla",
    prepTimeMinutes: 12,
    whyThisMeal: "Recommended because sweet apple with melted cheese is a surprising combo many children enjoy.",
    ingredients: ["Tortilla", "Grated cheddar", "Thin apple slices", "Butter"],
    steps: ["Layer cheese and apple on half the tortilla.", "Fold and cook in butter until crisp.", "Cut into triangles."],
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Lentil & Carrot Soup",
    prepTimeMinutes: 30,
    whyThisMeal: "Recommended because blended soup is warm, soothing, and packed with iron-rich lentils.",
    ingredients: ["Red lentils", "Carrot", "Onion", "Vegetable stock", "Cumin"],
    steps: ["Simmer lentils with chopped veg and stock.", "Blend until smooth.", "Serve with bread fingers for dipping."],
    healthyTip: "Let it cool to kid-safe temperature before serving.",
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Chicken & Veggie Skewers",
    prepTimeMinutes: 22,
    whyThisMeal: "Recommended because food on a stick turns an ordinary meal into an interactive experience.",
    ingredients: ["Cooked chicken cubes", "Cherry tomatoes", "Cheese cubes", "Cucumber chunks"],
    steps: ["Thread ingredients onto blunt skewers.", "Serve with a mild yogurt dip.", "Supervise closely while eating."],
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Overnight Weetbix Jars",
    prepTimeMinutes: 5,
    whyThisMeal: "Recommended because no-cook prep saves busy mornings and chia adds staying power.",
    ingredients: ["Weetbix or oats", "Milk", "Yogurt", "Mashed banana", "Chia seeds"],
    steps: ["Layer ingredients in a jar.", "Refrigerate overnight or 2+ hours.", "Top with fruit before serving."],
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Mini Pizza Faces",
    prepTimeMinutes: 20,
    whyThisMeal: "Recommended because decorating their own pizza gives children control and sparks creativity.",
    ingredients: ["English muffins", "Tomato passata", "Mozzarella", "Veg slices for faces"],
    steps: ["Spread passata on muffin halves.", "Add cheese and veg to make silly faces.", "Grill until cheese melts."],
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Coconut Chicken Curry (Mild)",
    prepTimeMinutes: 28,
    whyThisMeal: "Recommended because mild coconut curry introduces new flavours in a creamy, non-spicy sauce.",
    ingredients: ["Chicken strips", "Coconut milk", "Mild curry paste", "Peas", "Rice"],
    steps: ["Simmer chicken in coconut milk and a tiny amount of paste.", "Add peas near the end.", "Serve over rice."],
    healthyTip: "Start with just a quarter teaspoon of paste — you can always add more for adults.",
  },
  {
    title: "Today's Healthy Lunch",
    subtitle: "Tuna & White Bean Salad",
    prepTimeMinutes: 12,
    whyThisMeal: "Recommended because this no-cook salad is quick, protein-rich, and great for warm days.",
    ingredients: ["Canned tuna", "Cannellini beans", "Olive oil", "Lemon", "Cherry tomatoes"],
    steps: ["Drain tuna and rinse beans.", "Toss with halved tomatoes, oil, and lemon.", "Serve with crackers or bread."],
  },
];

export const PLAY_ALTERNATES: Omit<DailyBriefPlay, "imageData">[] = [
  {
    title: "Indoor Obstacle Adventure",
    materials: ["Cushions", "Masking tape", "Small toy to carry"],
    instructions: ["Create a path with cushions to climb over.", "Tape a zigzag line to walk along.", "Carry a toy through without dropping it.", "Cheer each completed lap!"],
    detailedInstructions: [
      "Clear a safe strip of floor space in the living room.",
      "Lay cushions as low 'mountains' to step over — keep heights toddler-safe.",
      "Use masking tape to mark a zigzag balance line on the floor.",
      "Place a favourite small toy at the start line.",
      "Show your child how to climb, balance, and carry the toy through.",
      "Time one lap or count steps together for extra fun.",
      "Take turns being the leader and the cheer squad.",
      "Cool down with water and put cushions back when finished.",
    ],
    skillsDeveloped: ["Balance", "Planning", "Gross motor"],
    durationMinutes: 20,
    indoorOutdoor: "indoor",
    ageRecommendation: "2-6 years",
    reason: "Recommended because obstacle courses burn energy and build confidence in movement.",
  },
  {
    title: "Sound Treasure Hunt",
    materials: ["Two small containers", "Rice or pasta", "Matching small toys"],
    instructions: ["Make two shakers with the same toy hidden inside.", "Mix them up and shake to listen.", "Find the pair that sounds the same."],
    skillsDeveloped: ["Listening", "Memory", "Turn-taking"],
    durationMinutes: 15,
    indoorOutdoor: "indoor",
    ageRecommendation: "2-5 years",
    reason: "Recommended because listening games sharpen auditory skills through play.",
  },
  {
    title: "Sticker Story Journey",
    materials: ["Large paper", "Stickers", "Crayons or markers"],
    instructions: ["Draw a winding path on paper.", "Place stickers as landmarks.", "Tell a story about visiting each place.", "Add new stickers for the next chapter."],
    skillsDeveloped: ["Language", "Creativity", "Fine motor"],
    durationMinutes: 25,
    indoorOutdoor: "indoor",
    ageRecommendation: "3-6 years",
    reason: "Recommended because combining art and storytelling deepens imaginative thinking.",
  },
  {
    title: "Kitchen Band Parade",
    materials: ["Pots", "Wooden spoons", "Plastic containers", "Rice shakers"],
    instructions: ["Assign each pot a different sound.", "Practice a simple beat together.", "March around the room in a parade.", "Take turns being the band leader."],
    skillsDeveloped: ["Rhythm", "Coordination", "Imagination"],
    durationMinutes: 15,
    indoorOutdoor: "indoor",
    ageRecommendation: "2-5 years",
    reason: "Recommended because music and movement together support body awareness and joy.",
  },
  {
    title: "Blanket Fort Campout",
    materials: ["Blankets", "Chairs", "Clothes pegs", "Torch", "Books"],
    instructions: ["Build a fort together.", "Add cushions and a soft blanket inside.", "Read a story by torchlight.", "Play pretend camping with snacks."],
    skillsDeveloped: ["Cooperation", "Problem solving", "Imaginative play"],
    durationMinutes: 30,
    indoorOutdoor: "indoor",
    ageRecommendation: "2-6 years",
    reason: "Recommended because cosy spaces invite calm connection and creative role-play.",
  },
  {
    title: "Nature Colour Walk",
    materials: ["Paper bag or basket", "Optional colour chart"],
    instructions: ["Head outside for a short walk.", "Find one item for each colour: red, green, brown.", "Talk about textures — smooth, rough, soft.", "Display finds at home."],
    skillsDeveloped: ["Observation", "Language", "Gross motor"],
    durationMinutes: 25,
    indoorOutdoor: "outdoor",
    ageRecommendation: "2-6 years",
    reason: "Recommended because outdoor exploration builds vocabulary and curiosity about the world.",
  },
  {
    title: "Playdough Bakery Shop",
    materials: ["Playdough", "Rolling pin", "Cookie cutters", "Toy plates"],
    instructions: ["Set up a pretend bakery counter.", "Roll and cut 'biscuits' and 'cakes'.", "Take orders and serve customers.", "Count how many items you sell."],
    skillsDeveloped: ["Fine motor", "Math", "Social play"],
    durationMinutes: 30,
    indoorOutdoor: "indoor",
    ageRecommendation: "2-5 years",
    reason: "Recommended because pretend play strengthens hand muscles and early number skills.",
  },
  {
    title: "Balloon Keep-Up Challenge",
    materials: ["Balloon", "Optional: paper plates as bats"],
    instructions: ["Blow up a balloon.", "Keep it in the air without letting it touch the floor.", "Count aloud how many taps you manage.", "Try using plates as paddles."],
    skillsDeveloped: ["Hand-eye coordination", "Counting", "Gross motor"],
    durationMinutes: 15,
    indoorOutdoor: "either",
    ageRecommendation: "3-6 years",
    reason: "Recommended because balloon play is safe indoors and builds tracking skills.",
  },
  {
    title: "Ice Cube Excavation",
    materials: ["Frozen ice block with toy inside", "Warm water dropper", "Salt", "Small tools"],
    instructions: ["Freeze a small toy in water overnight.", "Use droppers and salt to melt the ice.", "Excavate the treasure together.", "Talk about melting and freezing."],
    skillsDeveloped: ["Science curiosity", "Patience", "Fine motor"],
    durationMinutes: 25,
    indoorOutdoor: "indoor",
    ageRecommendation: "3-6 years",
    reason: "Recommended because sensory science play keeps little hands busy and minds wondering.",
  },
  {
    title: "Shadow Puppet Theatre",
    materials: ["Torch or lamp", "Blank wall", "Hands or cut-out shapes"],
    instructions: ["Darken the room slightly.", "Shine a light on the wall.", "Make shadow animals with your hands.", "Put on a short show for the family."],
    skillsDeveloped: ["Creativity", "Storytelling", "Fine motor"],
    durationMinutes: 20,
    indoorOutdoor: "indoor",
    ageRecommendation: "3-6 years",
    reason: "Recommended because shadow play turns a simple evening into magical storytelling.",
  },
  {
    title: "Laundry Basket Boat Ride",
    materials: ["Laundry basket", "Rope or scarf", "Pillows"],
    instructions: ["Line the basket with soft pillows.", "Pull your child gently around the room.", "Pretend you're sailing to different islands.", "Stop at each 'island' for a mini task."],
    skillsDeveloped: ["Balance", "Imagination", "Trust"],
    durationMinutes: 15,
    indoorOutdoor: "indoor",
    ageRecommendation: "2-4 years",
    reason: "Recommended because gentle movement games build vestibular sense and connection.",
  },
  {
    title: "Garden Bug Detective",
    materials: ["Magnifying glass", "Notebook", "Pencil"],
    instructions: ["Look under pots and leaves for insects.", "Draw what you find.", "Count legs and talk about colours.", "Release creatures back carefully."],
    skillsDeveloped: ["Observation", "Drawing", "Nature awareness"],
    durationMinutes: 30,
    indoorOutdoor: "outdoor",
    ageRecommendation: "3-6 years",
    reason: "Recommended because bug hunting turns the garden into a living science lab.",
  },
  {
    title: "Tape Road City",
    materials: ["Masking tape", "Toy cars", "Blocks for buildings"],
    instructions: ["Tape roads on the floor.", "Add block buildings and parking spots.", "Drive cars following road rules.", "Create a story about where each car goes."],
    skillsDeveloped: ["Planning", "Fine motor", "Imaginative play"],
    durationMinutes: 25,
    indoorOutdoor: "indoor",
    ageRecommendation: "2-5 years",
    reason: "Recommended because building a city from tape and toys sparks hours of open-ended play.",
  },
  {
    title: "Yoga Animal Poses",
    materials: ["Clear floor space", "Optional: yoga mat"],
    instructions: ["Try cat, dog, tree, and butterfly poses.", "Hold each pose for three breaths.", "Make animal sounds together.", "Finish with a quiet star pose."],
    skillsDeveloped: ["Body awareness", "Calm regulation", "Flexibility"],
    durationMinutes: 15,
    indoorOutdoor: "either",
    ageRecommendation: "3-6 years",
    reason: "Recommended because animal yoga helps active children wind down while staying engaged.",
  },
  {
    title: "Water Pouring Station",
    materials: ["Bowls", "Cups", "Jugs", "Spoons", "Towels"],
    instructions: ["Set up containers at different heights.", "Pour water between them.", "Use spoons to transfer.", "Talk about full, empty, and overflow."],
    skillsDeveloped: ["Fine motor", "Math concepts", "Sensory exploration"],
    durationMinutes: 20,
    indoorOutdoor: "either",
    ageRecommendation: "2-5 years",
    reason: "Recommended because water play teaches measurement and concentration naturally.",
  },
  {
    title: "Dress-Up Fashion Show",
    materials: ["Old clothes", "Hats", "Scarves", "Optional music"],
    instructions: ["Pick outfits together.", "Walk a 'runway' across the room.", "Introduce each outfit with applause.", "Take photos of favourite looks."],
    skillsDeveloped: ["Self-expression", "Confidence", "Gross motor"],
    durationMinutes: 25,
    indoorOutdoor: "indoor",
    ageRecommendation: "2-6 years",
    reason: "Recommended because dress-up builds identity play and social confidence.",
  },
  {
    title: "Paper Aeroplane Contest",
    materials: ["Paper", "Masking tape for runway"],
    instructions: ["Fold simple paper planes together.", "Mark a start line with tape.", "Throw and measure how far they fly.", "Adjust folds and try again."],
    skillsDeveloped: ["Following steps", "Measurement", "Persistence"],
    durationMinutes: 20,
    indoorOutdoor: "either",
    ageRecommendation: "4-6 years",
    reason: "Recommended because building and testing planes teaches trial and error in a fun way.",
  },
  {
    title: "Sensory Rice Bin Dig",
    materials: ["Tray of dry rice", "Hidden small toys", "Cups and scoops"],
    instructions: ["Hide toys in a tray of rice.", "Dig with hands or scoops to find them.", "Sort treasures by type or colour.", "Bury them again for round two."],
    skillsDeveloped: ["Sensory processing", "Sorting", "Fine motor"],
    durationMinutes: 25,
    indoorOutdoor: "indoor",
    ageRecommendation: "2-5 years",
    reason: "Recommended because sensory bins calm busy hands while building focus.",
  },
];

export const LANGUAGE_ALTERNATES: DailyBriefDevelopment[] = [
  {
    domain: "Language",
    icon: "💬",
    insight: "Many children around this age enjoy naming familiar objects during daily routines.",
    tryToday: "At bath time, point and name five items: towel, duck, soap, cup, water.",
    reason: "Recommended because labelling everyday objects builds useful vocabulary in context.",
  },
  {
    domain: "Language",
    icon: "💬",
    insight: "Many children around this age begin joining two words together.",
    tryToday: "Model short phrases all day: 'more milk', 'big truck', 'go park'.",
    reason: "Recommended because hearing two-word models helps early sentence building.",
  },
  {
    domain: "Language",
    icon: "🐄",
    insight: "Many children around this age love copying animal sounds before real words.",
    tryToday: "Play sound bingo: make a moo, woof, or quack — your child copies and guesses.",
    reason: "Recommended because playful sounds strengthen mouth muscles and listening.",
  },
  {
    domain: "Language",
    icon: "💬",
    insight: "Many children around this age respond well to simple either-or questions.",
    tryToday: "Offer choices: 'Apple or banana?' 'Red cup or blue cup?' Wait for a word or point.",
    reason: "Recommended because choices invite communication without overwhelming pressure.",
  },
  {
    domain: "Language",
    icon: "📖",
    insight: "Many children around this age learn new words fastest through repetition in books.",
    tryToday: "Read the same short book twice — leave a word blank and let your child fill it in.",
    reason: "Recommended because predictable stories build confidence and word recall.",
  },
  {
    domain: "Language",
    icon: "🎵",
    insight: "Many children around this age pick up rhythm and rhyme before long sentences.",
    tryToday: "Sing a nursery rhyme and clap the beat. Pause before the last word of each line.",
    reason: "Recommended because rhyming songs support phonological awareness for later reading.",
  },
  {
    domain: "Language",
    icon: "👀",
    insight: "Many children around this age benefit from describing what you see together.",
    tryToday: "On a walk, take turns saying 'I see a…' — tree, dog, bus, flower.",
    reason: "Recommended because back-and-forth commenting mirrors real conversation patterns.",
  },
  {
    domain: "Language",
    icon: "🧸",
    insight: "Many children around this age talk more freely through a toy or puppet.",
    tryToday: "Use a soft toy to 'ask' simple questions: 'I'm hungry. What should I eat?'",
    reason: "Recommended because pretend voices reduce pressure and spark longer replies.",
  },
  {
    domain: "Language",
    icon: "✋",
    insight: "Many children around this age combine gesture and word before speaking clearly.",
    tryToday: "Practice waving, pointing, and signing 'more' and 'all done' during meals.",
    reason: "Recommended because gestures bridge the gap when words are still forming.",
  },
  {
    domain: "Language",
    icon: "🔢",
    insight: "Many children around this age enjoy counting alongside action words.",
    tryToday: "Count stairs, jumps, or spoon stirs aloud: 'One stir, two stir, three stir!'",
    reason: "Recommended because pairing numbers with movement makes language active and memorable.",
  },
  {
    domain: "Language",
    icon: "😊",
    insight: "Many children around this age are learning emotion words to express feelings.",
    tryToday: "Name feelings in the mirror: happy, tired, silly. Match faces to each word.",
    reason: "Recommended because emotion vocabulary supports self-regulation and empathy.",
  },
  {
    domain: "Language",
    icon: "🍳",
    insight: "Many children around this age learn verbs best when doing the action.",
    tryToday: "While cooking, narrate verbs: stir, pour, mix, chop. Let your child try each safely.",
    reason: "Recommended because action words stick when linked to real experiences.",
  },
  {
    domain: "Language",
    icon: "🌙",
    insight: "Many children around this age benefit from a calm recap of the day.",
    tryToday: "At bedtime, name three things you did today and ask 'What was your favourite?'",
    reason: "Recommended because daily recaps strengthen memory, sequencing, and reflection.",
  },
  {
    domain: "Language",
    icon: "🎨",
    insight: "Many children around this age describe colours before complex sentences.",
    tryToday: "While drawing, ask 'What colour is that?' and expand: 'Yes, a big blue sky!'",
    reason: "Recommended because expanding your child's words models richer sentences naturally.",
  },
  {
    domain: "Language",
    icon: "👂",
    insight: "Many children around this age need extra wait time after a question.",
    tryToday: "Ask one simple question and count silently to five before prompting again.",
    reason: "Recommended because extra pause time gives developing brains space to respond.",
  },
];

export function storyAlternates(profile: BriefProfile): Omit<DailyBriefStory, "illustrationData">[] {
  const child = profile.childNickname || "your little one";
  const age = profile.childAge ?? "2-5 years";

  return [
    {
      title: `${child} and the Friendly Cloud`,
      theme: "Friendship",
      reason: `Recommended because a gentle sky adventure helps ${child} settle with warmth at bedtime.`,
      ageSuitability: age,
      story: `One afternoon, ${child} noticed a small cloud shaped like a bunny drifting low across the sky. The cloud seemed shy, so ${child} whispered hello. To their delight, the cloud floated down until they could almost touch it — soft and cool like cotton wool. They played a quiet game of shadow shapes until the sun turned golden. "Come back tomorrow," ${child} called, and the cloud waved a wispy goodbye. That night, ${child} fell asleep smiling, wondering what shape the cloud would make next.`,
      lengthMinutes: 4,
      moral: "Friendship can begin with a single kind hello.",
    },
    {
      title: `${child}'s Garden Discovery`,
      theme: "Patience",
      reason: `Recommended because a nature story about waiting suits a calm bedtime for ${child}.`,
      ageSuitability: age,
      story: `${child} planted a seed in a little pot by the window. Every morning they checked — still brown soil. "Not yet," said Mum, kneeling beside them. Days passed until a tiny green curl pushed through. ${child} watered it gently and sang to it. When a bright yellow flower opened, ${child} clapped with pride. "We waited together," they said. The flower nodded in the breeze as if agreeing. Goodnight, ${child}.`,
      lengthMinutes: 4,
      moral: "Beautiful things often take time to grow.",
    },
    {
      title: `${child} Saves the Rainbow`,
      theme: "Kindness",
      reason: `Recommended because a colourful quest keeps ${child} engaged while teaching gentle values.`,
      ageSuitability: age,
      story: `After the rain, ${child} noticed the rainbow looked faint. A tiny voice explained that colours fade when people forget to be kind. ${child} set off with a pocket full of good deeds — sharing a toy, helping tidy up, and telling Dad he made the best sandwiches. With each kind act, a stripe of the rainbow glowed brighter. By bedtime, the sky blazed with colour, and ${child} felt warm inside too.`,
      lengthMinutes: 5,
      moral: "Small acts of kindness brighten the world.",
    },
    {
      title: `${child} and the Sleepy Train`,
      theme: "Routine",
      reason: `Recommended because a slow journey story helps ${child} transition toward sleep.`,
      ageSuitability: age,
      story: `The Sleepy Train arrived at ${child}'s bedroom window with a gentle chuff-chuff. Conductor Owl tipped his hat and invited ${child} aboard. They passed through Blanket Valley, Pillow Hill, and the Tunnel of Yawns. At each stop, ${child} snuggled deeper into soft seats. The stars came out one by one. "Last stop: Dreamland," hooted the owl. ${child} smiled and closed their eyes as the train rolled on into the night.`,
      lengthMinutes: 4,
      moral: "Gentle routines carry us safely to sleep.",
    },
    {
      title: `${child}'s Moonlight Picnic`,
      theme: "Wonder",
      reason: `Recommended because a peaceful moonlit scene creates a soothing end to ${child}'s day.`,
      ageSuitability: age,
      story: `When the moon rose round and silver, ${child} spread a blanket in the garden. Crickets played a soft song. A moth with dusty wings landed nearby, curious about the crumbs. ${child} shared quietly and watched the moon climb higher. Fireflies blinked like tiny lanterns. Mum wrapped a shawl around ${child}'s shoulders. "The night is full of friends," she whispered. ${child} yawned, full of wonder and ready for bed.`,
      lengthMinutes: 4,
      moral: "The quiet world at night holds its own magic.",
    },
    {
      title: `${child} and the Brave Little Lantern`,
      theme: "Courage",
      reason: `Recommended because a story about facing small fears supports ${child}'s emotional growth.`,
      ageSuitability: age,
      story: `${child} had a lantern with a warm golden glow. One evening the hallway seemed very dark. "I'm a little scared," ${child} admitted. The lantern flickered as if to say, "We'll go together." Step by step they walked down the hall, the light bouncing ahead. Shadows turned out to be coats and shoes — nothing scary at all. ${child} laughed with relief. That night they placed the lantern on the shelf and slept peacefully, proud of being brave together.`,
      lengthMinutes: 5,
      moral: "Facing fears together makes us stronger.",
    },
    {
      title: `${child}'s Ocean of Dreams`,
      theme: "Imagination",
      reason: `Recommended because imaginative sea adventures give ${child} rich images for dreamtime.`,
      ageSuitability: age,
      story: `${child} closed their eyes and imagined an ocean made of soft blue silk. Friendly dolphins leaped alongside a little boat. Below, coral castles shimmered with fish in every colour. A seahorse bowed and offered a ride through swaying kelp forests. The waves hummed a lullaby. When the boat reached a quiet lagoon, the stars reflected on the water like floating diamonds. ${child} drifted into dreams, sailing on.`,
      lengthMinutes: 4,
      moral: "Imagination can take us anywhere we wish to go.",
    },
    {
      title: `${child} Helps the Worry Bugs`,
      theme: "Emotions",
      reason: `Recommended because naming worries helps ${child} feel understood before sleep.`,
      ageSuitability: age,
      story: `Tiny Worry Bugs sometimes visited ${child} at bedtime — buzzing thoughts about tomorrow. One night ${child} decided to talk to them. "What's wrong?" they asked kindly. The bugs explained they just wanted to be heard. ${child} breathed slowly in and out, and told each worry they would handle it in the morning. One by one the bugs curled up in soft leaf beds and fell asleep. ${child} did too, feeling lighter.`,
      lengthMinutes: 5,
      moral: "Sharing worries makes them smaller.",
    },
    {
      title: `${child} and the Star Who Forgot to Shine`,
      theme: "Belonging",
      reason: `Recommended because a story about finding your place builds ${child}'s confidence.`,
      ageSuitability: age,
      story: `High above, a little star felt dim compared to the others. ${child} spotted it from the window and waved. "You're shining enough for me," they called. The star twinkled — surprised and happy. Night after night ${child} looked for their star friend. Together they learned that you don't have to be the brightest to matter. You just have to be yourself. Sleep well, ${child}. Your star is watching over you.`,
      lengthMinutes: 4,
      moral: "Everyone has a special light of their own.",
    },
    {
      title: `${child}'s Teddy Bear Expedition`,
      theme: "Adventure",
      reason: `Recommended because a cosy adventure with a familiar friend feels safe for ${child}.`,
      ageSuitability: age,
      story: `${child} and Teddy packed a tiny backpack with a biscuit and a map drawn in crayon. Their expedition crossed the Mountain of Pillows and the River of Rug. They discovered a cave under the bed where lost socks lived peacefully. Teddy led the way with a torch made of a phone light. Before returning home, they shared the biscuit and stamped their expedition passport. "Best adventure ever," yawned ${child}, hugging Teddy tight.`,
      lengthMinutes: 5,
      moral: "Adventure is wonderful — especially with a friend.",
    },
    {
      title: `${child} and the Whispering Forest`,
      theme: "Nature",
      reason: `Recommended because gentle nature imagery helps ${child} relax body and mind.`,
      ageSuitability: age,
      story: `In the Whispering Forest, leaves told stories when the wind passed through. ${child} walked a mossy path barefoot, feeling cool earth beneath their toes. A deer watched quietly from between birch trees. An owl hooted a welcome. ${child} sat on a log and listened — the forest whispered about slow growth, deep roots, and seasons changing. Feeling peaceful, ${child} walked home as fireflies lit the path. The forest waved goodnight with rustling branches.`,
      lengthMinutes: 5,
      moral: "Nature teaches us to slow down and listen.",
    },
    {
      title: `${child}'s Superpower of Kindness`,
      theme: "Empathy",
      reason: `Recommended because celebrating kindness gives ${child} a positive note to end the day.`,
      ageSuitability: age,
      story: `${child} discovered they had a superpower — not flying or super strength, but kindness. When they shared, things glowed. When they helped, flowers bloomed. When they said sorry, grey clouds parted. By evening the whole house felt warmer. Mum tucked ${child} in and said, "Your kindness made today better." ${child} smiled. "I'll use my superpower again tomorrow," they murmured, already half asleep.`,
      lengthMinutes: 4,
      moral: "Kindness is a superpower we all carry.",
    },
    {
      title: `${child} and the Midnight Library`,
      theme: "Curiosity",
      reason: `Recommended because a magical library story sparks ${child}'s love of stories themselves.`,
      ageSuitability: age,
      story: `When the clock struck bedtime, a tiny door appeared in ${child}'s bookshelf. Inside was the Midnight Library, where books floated gently like kites. A friendly librarian cat purred, "Choose any story to dream inside." ${child} picked a book about flying ships and climbed aboard. Pages turned into clouds. Characters waved hello. When the book closed softly, ${child} was back in bed, carrying the adventure into dreams.`,
      lengthMinutes: 5,
      moral: "Stories open doors to endless worlds.",
    },
    {
      title: `${child} Builds a Bridge`,
      theme: "Cooperation",
      reason: `Recommended because teamwork themes mirror everyday family life for ${child}.`,
      ageSuitability: age,
      story: `Two sides of a stream needed connecting, and ${child} wanted to visit the meadow beyond. With blocks, planks, and help from Mum and Dad, they built a bridge together. It wobbled at first, then grew strong. ${child} walked across carefully, proud of every hand that helped. On the other side, wildflowers nodded in the breeze. "We did it together," ${child} said. That night they dreamed of building bridges everywhere they went.`,
      lengthMinutes: 4,
      moral: "Working together makes hard things possible.",
    },
    {
      title: `${child}'s Dragon Who Lost Their Roar`,
      theme: "Self-acceptance",
      reason: `Recommended because a gentle dragon tale encourages ${child} to embrace differences.`,
      ageSuitability: age,
      story: `A small dragon named Puff could only squeak instead of roar. ${child} found Puff hiding behind a rock, embarrassed. "Your squeak is perfect," ${child} said, and asked Puff to try. Together they squeaked a song that made birds dance. Other dragons joined in, each with their own sound. Puff learned that being different wasn't wrong — it was wonderful. ${child} hugged Puff goodnight and fell asleep smiling.`,
      lengthMinutes: 5,
      moral: "Our differences make us special.",
    },
  ];
}
